### ISSUE TITLE
Top Header tabs

### ISSUE THREAD

**Issue by cshjnim** [cshjnim/Project_Golden_Geese#19]
- [x] function for user to save things, undo, redo
- [x] function to login and recall all saved info & work
WHEN POSSIBLE, not necessary:
- [ ] function to save files locally
- [ ] function to open local txt files

**Comment by wsatchmo** [comment]
Has basic functionality; could use a more detailed pass in the future for File>Save, instead of just autosaving a single file

**Comment by wsatchmo** [comment]
Not doing local saving and opening for now  [NOT REQUIRED]
